<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Branch Sales Targets Report</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-size: 12px;
            color: #333;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #4CAF50;
            padding-bottom: 10px;
        }
        .header h2 {
            margin: 0;
            color: #4CAF50;
            font-size: 22px;
        }
        .header p {
            margin: 5px 0 0 0;
            color: #777;
            font-size: 14px;
        }
        .meta-info {
            margin-bottom: 20px;
            font-size: 11px;
            color: #555;
        }
        .meta-info table {
            width: 100%;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table.data-table th, table.data-table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        table.data-table th {
            background-color: #4CAF50;
            color: white;
            font-weight: bold;
            font-size: 11px;
        }
        table.data-table tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
        .badge {
            padding: 3px 6px;
            border-radius: 3px;
            font-size: 10px;
            font-weight: bold;
            display: inline-block;
        }
        .badge-success {
            background-color: #d4edda;
            color: #155724;
        }
        .badge-primary {
            background-color: #cce5ff;
            color: #004085;
        }
        .badge-warning {
            background-color: #fff3cd;
            color: #856404;
        }
        .badge-secondary {
            background-color: #e2e3e5;
            color: #383d41;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #aaa;
            border-top: 1px solid #eee;
            padding-top: 5px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>Branch Sales Targets Report</h2>
        <p>Generated on {{ date('d M Y h:i A') }}</p>
    </div>

    <div class="meta-info">
        <table>
            <tr>
                <td><strong>Report Type:</strong> Registry List</td>
                <td class="text-right"><strong>Generated By:</strong> {{ auth()->user()->first_name }} {{ auth()->user()->last_name }}</td>
            </tr>
        </table>
    </div>

    <table class="data-table">
        <thead>
            <tr>
                <th width="5%">ID</th>
                <th width="15%">Branch</th>
                <th width="15%">Period</th>
                <th width="10%" class="text-right">Target Qty</th>
                <th width="10%" class="text-right">Achieved Qty</th>
                <th width="10%" class="text-right">Achieved %</th>
                <th width="10%" class="text-right">Incentive</th>
                <th width="10%" class="text-right">Extra Comm.</th>
                <th width="10%" class="text-right">Total Bonus</th>
                <th width="10%" class="text-center">Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($targets as $target)
                <tr>
                    <td>{{ $target->id }}</td>
                    <td>{{ $target->branch ? $target->branch->name : 'N/A' }}</td>
                    <td>{{ $target->period_month }} {{ $target->period_year }}</td>
                    <td class="text-right">{{ number_format($target->target_quantity, 2) }}</td>
                    <td class="text-right">{{ number_format($target->achieved_quantity, 2) }}</td>
                    <td class="text-right">{{ number_format($target->achievement_percentage, 1) }}%</td>
                    <td class="text-right">৳{{ number_format($target->incentive_amount, 2) }}</td>
                    <td class="text-right">৳{{ number_format($target->commission_per_extra_sale, 2) }}</td>
                    <td class="text-right"><strong>৳{{ number_format($target->total_achieved_bonus, 2) }}</strong></td>
                    <td class="text-center">
                        @if($target->status == 'achieved')
                            <span class="badge badge-success">Achieved</span>
                        @elseif($target->status == 'active')
                            <span class="badge badge-primary">Active</span>
                        @elseif($target->status == 'expired')
                            <span class="badge badge-secondary">Expired</span>
                        @else
                            <span class="badge badge-warning">Inactive</span>
                        @endif
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="10" class="text-center">No sales targets found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Page 1 of 1 &copy; {{ date('Y') }} ERP System. All rights reserved.
    </div>
</body>
</html>
