<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Category Sales Report</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; margin: 0; padding: 20px; font-size: 11px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #444; padding-bottom: 10px; }
        .header h1 { margin: 0; font-size: 20px; text-transform: uppercase; }
        .report-info { margin-bottom: 20px; }
        .report-info p { margin: 2px 0; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ccc; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; font-weight: bold; }
        .text-end { text-align: right; }
        .footer { margin-top: 30px; text-align: center; font-size: 10px; color: #777; border-top: 1px solid #ccc; padding-top: 10px; }
        .summary-box { background-color: #f9f9f9; padding: 15px; border-radius: 5px; margin-bottom: 20px; border: 1px solid #ddd; }
        .summary-box h3 { margin-top: 0; font-size: 14px; border-bottom: 1px solid #ddd; padding-bottom: 5px; }
        .summary-grid { display: block; width: 100%; }
        .summary-item { display: inline-block; width: 30%; margin-right: 3%; vertical-align: top; }
        .summary-label { display: block; font-weight: bold; color: #666; margin-bottom: 3px; }
        .summary-value { display: block; font-size: 14px; color: #000; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Category Wise Sales Report</h1>
        <p>Generated on: {{ date('d-m-Y H:i A') }}</p>
    </div>

    <div class="report-info">
        <p><strong>Date Range:</strong> {{ $startDate->format('d-m-Y') }} to {{ $endDate->format('d-m-Y') }}</p>
    </div>

    <div class="summary-box">
        <h3>Report Summary</h3>
        <div class="summary-grid">
            <div class="summary-item">
                <span class="summary-label">Total Qty Sold:</span>
                <span class="summary-value">{{ $data->sum('quantity_sold') }}</span>
            </div>
            <div class="summary-item">
                <span class="summary-label">Total Revenue:</span>
                <span class="summary-value">{{ number_format($data->sum('revenue'), 2) }} TK</span>
            </div>
            <div class="summary-item">
                <span class="summary-label">Total Profit:</span>
                <span class="summary-value">{{ number_format($data->sum('profit'), 2) }} TK</span>
            </div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Category Name</th>
                <th class="text-end">Product Count</th>
                <th class="text-end">Qty Sold</th>
                <th class="text-end">Revenue</th>
                <th class="text-end">Cost</th>
                <th class="text-end">Profit</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $categoryId => $item)
                <tr>
                    <td>{{ $item['category_name'] }}</td>
                    <td class="text-end">{{ $item['product_count'] }}</td>
                    <td class="text-end">{{ $item['quantity_sold'] }}</td>
                    <td class="text-end">{{ number_format($item['revenue'], 2) }} TK</td>
                    <td class="text-end">{{ number_format($item['cost'], 2) }} TK</td>
                    <td class="text-end">{{ number_format($item['profit'], 2) }} TK</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by {{ auth()->user()->name ?? 'System' }} | © {{ date('Y') }} All Rights Reserved.</p>
    </div>
</body>
</html>
