<!DOCTYPE html>
<html>
<head>
    <title>Money Receipt Report</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 10px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 5px; text-align: left; }
        th { background-color: #2d5a4c; color: white; font-weight: bold; text-transform: uppercase; font-size: 8px; }
        .header { text-align: center; margin-bottom: 20px; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: right; font-size: 8px; }
        .text-center { text-align: center; }
        .text-end { text-align: right; }
        .fw-bold { font-weight: bold; }
        .bg-light { background-color: #f8f9fa; }
    </style>
</head>
<body>
    <div class="header">
        <h2>Money Receipt Report</h2>
        <p>Printed on: {{ date('d/m/Y H:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th class="text-center">#</th>
                <th>Receipt No</th>
                <th>Receipt Date</th>
                <th>Invoice Date</th>
                <th>Customer</th>
                <th>Outlet</th>
                <th>Sales Invoice</th>
                <th class="text-end">Due Amount</th>
                <th class="text-end">Paid Amount</th>
                <th>Account</th>
                <th>Collector</th>
            </tr>
        </thead>
        <tbody>
            @foreach($receipts as $index => $receipt)
                <tr>
                    <td class="text-center">{{ $index + 1 }}</td>
                    <td class="fw-bold">{{ $receipt->payment_reference }}</td>
                    <td>{{ \Carbon\Carbon::parse($receipt->payment_date)->format('d/m/Y') }}</td>
                    <td>{{ $receipt->invoice ? \Carbon\Carbon::parse($receipt->invoice->issue_date)->format('d/m/Y') : '-' }}</td>
                    <td>{{ $receipt->customer->name ?? 'Walk-in' }}</td>
                    <td>{{ $receipt->pos->branch->name ?? $receipt->invoice->pos->branch->name ?? '-' }}</td>
                    <td>{{ $receipt->invoice->invoice_number ?? '-' }}</td>
                    <td class="text-end">{{ number_format($receipt->invoice->due_amount ?? 0, 2) }}</td>
                    <td class="text-end fw-bold">{{ number_format($receipt->amount, 2) }}</td>
                    <td>{{ $receipt->payment_method }}</td>
                    <td>{{ $receipt->creator->name ?? '-' }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot class="bg-light">
            <tr class="fw-bold">
                <td colspan="8" class="text-end">Grand Total Paid</td>
                <td class="text-end">৳ {{ number_format($totalAmount, 2) }}</td>
                <td colspan="2"></td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        Generated by ERP System
    </div>
</body>
</html>
